project_name: slack-grafana-image-renderer-picker
env:
  - GO111MODULE=on
builds:
  - main: ./cmd/grasla
    id: "grasla"
    binary: grasla
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    builds:
      - grasla
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - CREDITS
      - config.yaml
release:
  prerelease: auto
